-- Add metadata columns to relevant tables
ALTER TABLE posts ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';
ALTER TABLE comments ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';
ALTER TABLE anime ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';
ALTER TABLE polls ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';
ALTER TABLE watchlist ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';